config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'

  resources :movies do
    post :result, on: :collection
    patch :add_to_favorites, on: :member
    get :sort_all, on: :collection
    resources :reviews do
      patch :report, on: :member
    end
    resources :ratings
  end

  devise_for :users
  resources :users, only: [:show]

  namespace :api do
    namespace :v1, defaults:{ format: :json } do
       resources :movies, only: [:index, :show]
    end
  end

  resources :actors, only: [:show]

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  GENRES = %w(Action Horror Comedy Thriller Romance Sci-Fi Sports Tragedy Animated)
  MOVIE_TYPES = %w(latest featured all)
  RESULTS_PER_PAGE = 8
  ORDERING_FIELDS = %w(rating release)
  ORDERS = %w(ascending descending)

  paginates_per RESULTS_PER_PAGE

  validates :title, :description, :release_date, :trailer_url, presence: true
  validates :title, uniqueness: true, length: { maximum: 50 }
  validates :description, length: { maximum: 255 }
  validates :genre, length: { maximum: 20 }
  validates :duration, length: { maximum: 5 }
  validates :trailer_url, length: { maximum: 1000 }
  validates :duration, numericality: { greater_than_or_equal_to: 0 }

  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :appearances, dependent: :destroy
  has_many :actors, through: :appearances
  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :favorite_movies, dependent: :destroy

  accepts_nested_attributes_for :attachments, allow_destroy: true , reject_if: proc { |attributes| attributes['image'].blank? }

  scope :latest, -> { order(release_date: :desc) }
  scope :approved, -> { where(approved: true) }
  scope :featured, -> { where(featured: true).order(updated_at: :desc) }
  scope :top, -> { joins(:ratings).where('movies.approved = true AND ratings.score > 0').group('movies.id').order('avg(ratings.score) desc') }
  scope :waiting_for_approval, -> { where(approved: false) }
  scope :oldest, -> { order(release_date: :asc) }
  scope :lowest_rated, -> { joins(:ratings).where('movies.approved = true AND ratings.score > 0').group('movies.id').order('avg(ratings.score) asc') }

  def image_path
    first_attachment = attachments.first
    first_attachment ? first_attachment.image.url(:medium) : 'medium/missing.png'
  end

  def self.get_movies(type_param)
    if type_param.in? MOVIE_TYPES
      movies = self.approved.latest if type_param == 'latest'
      movies = self.approved.featured if type_param == 'featured'
      movies = self.approved.all if type_param == 'all'
    else
      movies = self.approved.all
    end
    movies
  end

  def display_actors
    self.actors.collect(&:full_name).join(',')
  end

  def has_favorite?(user)
    self.favorite_movies.where(user: user).present?
  end

  def self.default_search_options(parameters)
    {
      order: 'updated_at DESC',
      with: { approved: true },
      conditions: {},
      sql: { include: [:attachments] },
      page: parameters[:page],
      per_page: RESULTS_PER_PAGE
    }
  end

  def self.search_movies(parameters)
    search_options = Movie.default_search_options(parameters)

    search_options[:conditions][:title] = serialize_query_string(parameters[:title]) if parameters[:title].present?
    search_options[:conditions][:genre] = serialize_query_string(parameters[:genre]) if parameters[:genre].present?
    search_options[:conditions][:actor_name] = serialize_query_string(parameters[:actor_name]) if parameters[:actor_name].present?

    search_options[:with][:release_date] = date_range(parameters[:start_date], parameters[:end_date]) if parameters[:start_date].present?

    Movie.search(search_options)
  end

  def self.basic_search(parameters)
    Movie.search(serialize_query_string(parameters[:search]), with: { approved: true }, order: 'updated_at DESC', page: parameters[:page], per_page: RESULTS_PER_PAGE, sql: { include: [:attachments] })
  end

  def movie_hash(base_url)
    movie_attachments = []

    attachments.each do |attachment|
      movie_attachments << [base_url, attachment.image.url(:medium)].join
    end

    {
      movie_details: self,
      actors: actors.pluck(:id, :first_name, :last_name, :gender),
      reviews: reviews.pluck(:id, :comment),
      attachments: movie_attachments
    }
  end

  def self.date_range(start_date, end_date)
    if start_date.present? && end_date.present?
     validate_date(start_date)..validate_date(end_date)
    elsif start_date.present?
     validate_date(start_date)..Date.today
    end
  end

  def self.validate_date(date)
    begin
      Date.parse(date)
    rescue
      Date.today
    end
  end

  def self.index_movies(params)
    if params[:search].present?
      Movie.basic_search(params)
    elsif params[:type].present?
      Movie.includes(:attachments).get_movies(params[:type]).page(params[:page])
    else
      Movie.search_movies(params)
    end
  end

  def self.order_movies(params)
    if params[:ordering_field].present? && params[:order].present?
      sorted_movies = Movie.oldest if params[:ordering_field] == 'release' && params[:order] == 'ascending'
      sorted_movies = Movie.latest if params[:ordering_field] == 'release' && params[:order] == 'descending'
      sorted_movies = Movie.top if params[:ordering_field] == 'rating' && params[:order] == 'descending'
      sorted_movies = Movie.lowest_rated if params[:ordering_field] == 'rating' && params[:order] == 'ascending'
    else
      sorted_movies = Movie.all
    end
    sorted_movies
  end

  def self.serialize_query_string(string)
    string.gsub(/[^0-9A-Za-z ]/, '')
  end

end

app/controllers/api/v1/movies_controller.rb
class Api::V1::MoviesController < Api::V1::BaseController
  before_action :get_movie, only: [:show]
  respond_to :json

  def index
    movies = unless params[:title] || params[:actor_name] || params[:genre]
      Movie.all
    else
      Movie.search_movies(params)
    end
    respond_with movies.page(params[:page])
  end

  def show
    respond_with @movie.movie_hash(request.env['HTTP_HOST'].to_s)
  end

  private

  def get_movie
    @movie = Movie.find(params[:id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :add_to_favorites]
  before_action :verify_movie_approval, only: [:show]
  before_action :get_latest_reviews, only: [:show]

  def index
    params[:type] = 'all' if all_params_nil?
    @movies = Movie.index_movies(params)
    @title = [display_movie_heading(params[:type]), 'Movies'].join(' ') if params[:type].present?
  end

  def new
    @movie = Movie.new
    @actors = Actor.all
    @title = 'New Movie'
  end

  def show
    @title = @movie.title
    if user_signed_in?
      @rating = Rating.set_rating(params[:id], current_user.id)
    end
    @average_rating = Rating.average(params[:id])
    @actors = @movie.actors
  end

  def edit
    @title = 'Edit Movie'
    @actors = Actor.all
    @selected = @movie.actors.pluck(:id)
    @actors_list = @actors.collect{|actor| [actor.full_name, actor.id]}
  end

  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        @actors = Actor.all
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        @actors = Actor.all
        @selected = @movie.actors.pluck(:id)
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def add_to_favorites
    return nil if @movie.has_favorite?(current_user)
    @favorite_movie = @movie.favorite_movies.new
    @favorite_movie.user = current_user
    @favorite_movie.save
  end

  def sort_all
    @sorted_movies = Movie.order_movies(params).page(params[:page])
  end

  private

    def set_movie
      @movie = Movie.includes(:reviews, :attachments, :ratings, :appearances, :favorite_movies).find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :release_date, :genre, :duration, :description, :trailer_url, :featured, :approved, attachments_attributes: [:id, :image, :_destroy], actor_ids: [])
    end

    def get_latest_reviews
      @reviews = @movie.reviews.latest.includes(:user, :reported_reviews)
    end

    def verify_movie_approval
      redirect_to root_path, alert: 'Movie can not be viewed before admin approval' unless @movie.approved?
    end

    def all_params_nil?
      params[:type].nil? && params[:search].blank? && params[:actor_name].nil? && params[:title].nil? && params[:start_date].nil? && params[:end_date].nil? && params[:genre].nil?
    end

end

app/helpers/movies_helper.rb
module MoviesHelper

  def escape_script_tags(embed_url)
    (embed_url.include?('<script>') && embed_url.include?('</script>')) ? html_escape(embed_url) : embed_url
  end

  def index_action?(action)
    action == 'index'
  end

end

app/views/movies/_actors.html.erb
<% if actors.empty? %>
  <div>Not Available</div>
<% else %>
  <% actors.each do |actor| %>
    <% actor == actors.last ? separator = '' : separator = ',' %>
    <%= link_to [actor.full_name, separator].join, actor_path(actor) %>
  <% end %>
<% end %>

app/views/movies/_form.html.erb
<div class='container'>
  <div class='row'>
    <div class='panel panel-default col-centered'>
      <div class='panel-heading'>
        <h1><%= action_name.capitalize %> Movie</h1>
      </div>
      <div class='panel-body'>
        <%= nested_form_for(@movie) do |f| %>
          <% if @movie.errors.any? %>
            <div id='error_explanation'>
              <h2><%= pluralize(@movie.errors.count, 'error') %> prohibited this movie from being saved:</h2>
              <ul>
              <% @movie.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class='field form-group'>
            <%= f.label :title %>
            <%= f.text_field :title, maxlength: 50, required: true, class: 'form-control' %>
          </div>
          <div class='field form-group'>
            <%= f.label :release_date, 'Released At' %>
            <%= f.date_field :release_date, maxlength: 50, required: true, class: 'form-control' %>
          </div>
          <div class='field form-group'>
            <%= f.label :genre %>
            <%= f.select :genre, Movie::GENRES, { prompt: 'Please select' }, { class: 'dropdown-toggle form-control' } %>
          </div>
          <div class='field form-group'>
            <%= f.label :duration %><i>(in minutes)</i>
            <%= f.number_field :duration, maxlength: 3, class: 'form-control' %>
          </div>
          <div class='field form-group'>
            <%= f.label :description, 'Summary' %>
            <%= f.cktext_area :description, class: 'form-control' %>
          </div>
          <div class='field form-group'>
            <%= f.label :trailer_url, 'Trailer Embed Code' %>
            <%= f.text_area :trailer_url, maxlength: 1000, class: 'form-control' %>
          </div>
          <div class='field form-group'>
            <%= f.label :posters, 'Movie Posters' %>
            <div>
              <%= f.fields_for :attachments do |attachment_form| %>
                <div class='row'>
                  <% if attachment_form.object.new_record? %>
                    <div class='col-md-6'><%= attachment_form.file_field :image, class: 'margin' %></div>
                  <% else %>
                    <div class='col-md-3'><%= image_tag attachment_form.object.image.url(:thumb) %></div>
                    <div class='col-md-3'><%= attachment_form.file_field :image, class: 'margin' %></div>
                  <% end %>
                  <div class='col-md-6'><%= attachment_form.link_to_remove '', class: 'btn btn-danger margin glyphicon glyphicon-remove' %></div>
                </div>
              <% end %>
            </div>
            <div>
              <%= f.link_to_add '', :attachments, class: 'btn btn-primary margin glyphicon glyphicon-plus' %>
            </div>
          </div>
          <div class='field form-group'>
            <%= f.label :actors, 'Starring Actors' %>
            <%= f.select :actor_ids, options_from_collection_for_select(@actors, 'id', 'full_name', @selected), {}, { multiple: true, class: 'form-control' } %>
          </div>
          <div class='actions form-group'>
            <%= f.submit button_title('Movie'), class: 'btn btn-success col-centered form-control' %>
          </div>
          <% if action_name == 'edit' %>
            <%= link_to 'Show', @movie, class: 'btn btn-default form-control margin' %>
          <% end %>
        <% end %>
        <%= link_to 'Back', movies_path, class: 'btn btn-default form-control margin' %>
      </div>
    </div>
  </div>
</div>

app/views/movies/_images.html.erb
<% attachments.in_groups_of(3, false).each do |attachment_group| %>
  <div class='row'>
    <% attachment_group.each do |attachment| %>
      <div class='col-md-4'>
        <%= image_tag(attachment.image.url(:thumb), class: 'poster_show img-responsive') %>
      </div>
    <% end %>
  </div>
  <hr/>
<% end %>

app/views/movies/_index_movies.html.erb
<% movies.in_groups_of(4, false).each do |movie_group| %>
  <div class='row'>
    <% movie_group.each do |movie| %>
      <div class='col-sm-3 large-font'>
        <%= link_to image_tag(movie.image_path, class: 'img-responsive'), movie %>
        <div class='bold large-font initial-align'>
          <%= movie.title %>
        </div>
        <% if top %>
          <div class='small-text'>
            <i>Average Rating: <%= Rating.average(movie.id) %></i>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <hr/>
<% end %>

<%= render partial:'shared/pagination', locals: { resources: movies } %>

app/views/movies/_order_bar.html.erb
<div class='row'>
  <div class='col-md-9 col-centered'>
    <%= form_tag(sort_all_movies_path, method: :get, remote: true) do %>

      <div class='col-sm-6'>
        <%= label_tag :ordering_field %>
        <%= select_tag :ordering_field, options_for_select(Movie::ORDERING_FIELDS.map{ |ordering_field| [ordering_field.titleize, ordering_field]}), class: 'form-control', prompt: 'Select Ordering Field' %>
      </div>

      <div class='col-sm-6'>
        <%= label_tag :order %>
        <%= select_tag :order, options_for_select(Movie::ORDERS.map{ |order| [order.titleize, order] }), class: 'form-control' %>
      </div>

      <div class='col-sm-12'>
        <%= submit_tag('Sort', class: 'btn btn-default form-control margin') %>
      </div>

    <% end %>
  </div>
</div>

app/views/movies/_ratings.html.erb
<h4> Your Rating </h4>
<% if user_signed_in? %>
  <div class="rating-stars" id="<%= create_star_id_url(@rating) %>" data-score="<%= @rating.score %>"></div>
  <%= hidden_field_tag 'rating_user_id', current_user.id %>
<% else %>
  <%= link_to 'Sign in to add ratings', new_user_session_path %>
<% end %>
<hr/>

app/views/movies/_search_bar.html.erb
<div class='row' id='search-bar'>
  <div class='panel panel-default col-centered'>
    <div class='panel-heading'>
      <div class='text-center'>
        <h1>Search</h1>
      </div>
    </div>

    <div class='panel-body'>
      <%= form_tag(movies_path, method: :get, remote: true) do %>
        <div class='row'>

          <div class='col-md-2'>
            <%= label_tag(:title) %>
            <%= text_field_tag(:title, nil, class: 'form-control search-field') %>
          </div>

          <div class='col-md-2'>
            <%= label_tag(:actor_name, 'Actor Name') %>
            <%= text_field_tag(:actor_name, nil, class: 'form-control search-field') %>
          </div>

          <div class='col-md-2'>
            <%= label_tag(:genre) %>
            <%= select_tag :genre, options_for_select(Movie::GENRES), class: 'form-control', prompt: 'Select a Genre' %>
          </div>

          <div class='col-md-3'>
            <%= label_tag(:start_date, 'Start Date') %>
            <%= date_field_tag :start_date, params[:start_date], class: 'form-control', placeholder: 'Search By Start Date' %>
          </div>

          <div class='col-md-3'>
            <%= label_tag(:end_date, 'Ending Date') %>
            <%= date_field_tag :end_date, params[:end_date], class: 'form-control', placeholder: 'Search By End Date' %>
          </div>

          <div class='row'>
            <div class='col-md-6 margin col-md-offset-3'>
               <%= submit_tag('Search', class: 'btn btn-success form-control') %>
            </div>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/add_to_favorites.js.erb
<% if @favorite_movie %>
  $("#favorite-btn").html('<span>Added to Favorites!</span>');
<% end %>

app/views/movies/edit.html.erb
<% title @title %>
<%= render 'form' %>

app/views/movies/index.html.erb
<div class='col-md-12 col-centered'>
  <% if params[:search].present? %>

    <% title 'Search' %>

    <div class='col-md-9 col-centered'>
      <%= render partial: 'search_bar' %>
    </div>

    <div id='index-display'>
      <h1 class='sub-heading'>Search Movies</h1>
      <%= render partial: 'index_movies', locals: { movies: @movies, top: nil } %>

    </div>

  <% elsif params[:type].present? %>

    <% title display_movie_heading(params[:type]) %>
    <% if params[:type] == 'all' %>
      <%= render partial: 'order_bar' %>
    <% end %>
    <div id='index-display'>
      <h1 class='sub-heading'>
        <%= display_movie_heading(params[:type]) %> Movies
      </h1>

      <%= render partial: 'index_movies', locals: { movies: @movies, top: nil } %>

    </div>

  <% else %>
    <div class='col-md-9 col-centered'>
      <%= render partial: 'search_bar' %>
    </div>
    <div id='index-display'></div>
  <% end %>

</div>

app/views/movies/index.js.erb
<% if @movies.present? %>
  $('#index-display').html("<h1 class='sub-heading'><%= @title %></div><hr/><%= j render partial: 'index_movies', locals: { movies: @movies, top: nil } %>");
<% else %>
  $('#index-display').html("<h1 class='sub-heading'>Movies</h1><hr/><div class='center-text'>No Results Found!</div>");
<% end %>

app/views/movies/new.html.erb
<% title @title %>
<%= render 'form' %>

app/views/movies/show.html.erb
<% title @title %>
<div class='container'>
  <div class='row'>
    <div class='col-sm-4'>
      <%= render partial: 'shared/carousel', locals: { attachments: @movie.attachments } %>
      <%= render partial: 'shared/modal_box' %>
      <div>
        <%= render partial: 'ratings' %>
      </div>

      <div id='favorite-btn'>

        <% if user_signed_in? %>
          <% unless current_user.has_already_favorite?(@movie) %>
            <%= form_for(@movie, url: add_to_favorites_movie_path(@movie), remote: true) do |f| %>
              <%= f.submit 'Add to Favorites', class: 'btn btn-default form-control' %>
            <% end %>
          <% else %>
            <span>Already a favorite!</span>
          <% end %>
        <% else %>
          <%= link_to 'Sign in to add to favorites', new_user_session_path %>
        <% end %>

      </div>
      <hr/>

      <div id='favorite-message'>
      </div>

      <% if user_signed_in? %>
        <div class='row'>
          <div class='col-md-6'>
            <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-default form-control' %>
          </div>

          <div class='col-md-6'>
            <%= link_to 'Delete', @movie, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default form-control' %>
          </div>
        </div>
        <hr/>
      <% end %>
      <div class='row'>
        <div class='col-md-12'>
          <%= link_to 'Back', movies_path, class: 'btn btn-default form-control' %>
        </div>
      </div>
    </div>

    <div class='col-sm-8'>
      <div class='row'>
        <div class='col-md-8'>
          <h1 id='movie-heading'><%= @title %></h1>
        </div>

        <div class='col-md-4'>
          <div class="average-stars" data-score="<%= @average_rating %>"></div>
        </div>
      </div>

      <div class='video-wrapper'>
        <h3>Trailer</h3>
        <%= display_value raw(escape_script_tags(@movie.trailer_url)) %>
      </div>

      <div class='row'>
        <div class='col-sm-4'>
          <h3>Release Date</h3>
          <%= display_value(date_display(@movie.release_date)) %>
        </div>

        <div class='col-sm-2'>
          <h3>Genre</h3>
          <%= display_value @movie.genre %>
        </div>

        <div class='col-sm-2'>
          <h3>Duration</h3>
          <%= display_value @movie.duration %> minutes
        </div>

        <div class='col-sm-4'>
          <h3>Actors</h3>
          <%= render partial:'actors', locals: { actors: @actors } %>
        </div>
      </div>

      <div id='movie-description'>
        <h2>Summary</h2>
        <%= display_value raw(@movie.description) %>
      </div>

      <h2>Reviews</h2>
      <div id='reviews'>
        <%= render @reviews %>
      </div>
      <div id='review-errors'>
      </div>
      <div id='review-form' class='hide-element'></div>
        <% if user_signed_in? %>
          <%= link_to 'Add Review', new_movie_review_path(@movie), remote: true, class: 'btn btn-default' %>
        <% end %>
    </div>

  </div>
</div>

app/views/movies/sort_all.js.erb
<% if @sorted_movies.present? %>
  $('#index-display').html("<h1 class='sub-heading'>Movies</div><hr/><%= j render partial: 'index_movies', locals: { movies: @sorted_movies, top: nil } %>");
<% else %>
  $('#index-display').html("<h1 class='sub-heading'>Movies</h1><hr/><div class='center-text'>No Results Found!</div>");
<% end %>