config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'

  resources :movies do
    post :result, on: :collection
    patch :add_to_favorites, on: :member
    get :sort_all, on: :collection
    resources :reviews do
      patch :report, on: :member
    end
    resources :ratings
  end

  devise_for :users
  resources :users, only: [:show]

  namespace :api do
    namespace :v1, defaults:{ format: :json } do
       resources :movies, only: [:index, :show]
    end
  end

  resources :actors, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_one :attachment, as: :attachable
  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :reported_reviews, dependent: :destroy
  has_many :favorite_movies, dependent: :destroy

  accepts_nested_attributes_for :attachment, allow_destroy: true, reject_if: proc { |attributes| attributes['image'].blank? }

  GENDERS =  %w(Male Female)

  validates :first_name, :last_name, presence: true, length: { maximum: 50 }
  validates :gender, presence: true, length: { maximum: 10 }, inclusion: { in: %w(Male Female), message: "%{value} is not valid" }

  def full_name
    [self.first_name , self.last_name].join(" ")
  end

  def profile_picture_path(style_parameter)
    self.attachment ? self.attachment.image.url(style_parameter) : '/assets/medium/missing.png'
  end

  def has_reported?(review)
    self.reported_reviews.where(review: review).present?
  end

  def get_favorite_movies
    movie_ids = self.favorite_movies.pluck(:movie_id)
    Movie.where(id: movie_ids)
  end

  def has_already_favorite?(movie)
    self.favorite_movies.where(movie: movie).present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def show
    @user_name = @user.full_name
    @favorite_movies = @user.get_favorite_movies.includes(:attachments).page(params[:page])
  end

  private
  def set_user
    @user = User.includes(:favorite_movies).find(params[:id])
  end

end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <div class='form-group'>
    <%= link_to 'Log In', new_session_path(resource_name), class: 'btn btn-default form-control' %>
  </div>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class='form-group'>
    <%= link_to 'Sign Up', new_registration_path(resource_name), class: 'btn btn-default form-control' %>
  </div>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <div class='form-group'>
    <%= link_to 'Forgot Your Password?', new_password_path(resource_name), class: 'btn btn-default form-control' %>
  </div>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <div class='form-group'>
    <%= link_to 'Didn\'t Receive Confirmation Instructions?', new_confirmation_path(resource_name), class: 'btn btn-default form-control' %>
  </div>
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <div class='form-group'>
    <%= link_to 'Didn\'t Receive Unlock Instructions?', new_unlock_path(resource_name), class: 'btn btn-default btn-wide' %>
  </div>
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <div class='form-group'>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: 'btn btn-default btn-wide' %>
    <% end -%>
  </div>
<% end -%>