config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  mount Ckeditor::Engine => '/ckeditor'

  resources :movies do
    post :result, on: :collection
    patch :add_to_favorites, on: :member
    get :sort_all, on: :collection
    resources :reviews do
      patch :report, on: :member
    end
    resources :ratings
  end

  devise_for :users
  resources :users, only: [:show]

  namespace :api do
    namespace :v1, defaults:{ format: :json } do
       resources :movies, only: [:index, :show]
    end
  end

  resources :actors, only: [:show]

end

app/views/shared/_alerts.html.erb
<% flash.each do |type, message| %>
  <div class="m-xs alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type='button' class='close' data-dismiss='alert'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_carousel.html.erb
<% if attachments.present? %>
<div id="myCarousel" class="carousel slide" data-ride="carousel">

  <ol class="carousel-indicators">
    <% attachments.each_with_index do |attachment, index| %>
      <li data-target='#myCarousel' data-slide-to=<%= index %> class='active'></li>
    <% end %>
  </ol>

  <div class="carousel-inner" role="listbox">
    <% attachments.each do |attachment| %>
      <% attachment == attachments.first ? carousel_class = 'item active' : carousel_class = 'item' %>
      <div class="<%= carousel_class %>">
        <%= image_tag(attachment.image.url(:medium), class: 'img-responsive') %>
      </div>
    <% end %>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<% else %>
  <%= image_tag 'medium/missing.png', alt: 'Profile Picture Unavailable', class: 'img-responsive' %>
<% end %>

app/views/shared/_footer.html.erb
<div>
  myIMDB, All Rights Reserved, 2016.
</div>

app/views/shared/_header.html.erb
<div id="navbar">
  <nav class="navbar navbar-inverse navbar-fixed-top" role='navigation'>
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Movie Time', root_path, class: 'navbar-brand' %>
        <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-menubuilder'>
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
      </div>
      <div class='collapse navbar-collapse navbar-menubuilder'>
        <ul class='nav navbar-nav navbar-right'>
          <li><%= render partial: 'layouts/search' %></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user.full_name, user_path(current_user) %></li>
            <li><%= link_to 'New Movie', new_movie_path, class: 'btn btn-default' %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_modal_box.html.erb
<div class='modal fade' id='image-modal' tabindex='-1' role='dialog' aria-labelledby='bootstrapModalLabel'>
 <div class='modal-dialog modal-width' role='document'>
   <div class='modal-content'>
     <div class='modal-header'>
       <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
         <span aria-hidden='true'>&times;</span>
       </button>
       <h3 class='modal-title' id='bootstrapModalLabel'>Image:</h3>
     </div>
     <div class='modal-body' align='center'>
       <div class='row'>
         <img id='img-modal' src='' style='width: 100%; height: 100%;'>
       </div>
     </div>
     <div class='modal-footer'>
     </div>
   </div>
 </div>
</div>

app/views/shared/_pagination.html.erb
<% if params[:controller] != 'home' && params[:controller] != 'users' && params[:controller] != 'actors' %>
  <div align='center'>
    <%= paginate resources, remote: true %>
  </div>
<% end %>